//
// AnimeSearchQueryOrderby.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Available Anime order_by properties */
public enum AnimeSearchQueryOrderby: String, Codable, CaseIterable {
    case malId = "mal_id"
    case title = "title"
    case type = "type"
    case rating = "rating"
    case startDate = "start_date"
    case endDate = "end_date"
    case episodes = "episodes"
    case score = "score"
    case scoredBy = "scored_by"
    case rank = "rank"
    case popularity = "popularity"
    case members = "members"
    case favorites = "favorites"
}
