//
// SearchQuerySort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Characters Search Query Sort */
public enum SearchQuerySort: String, Codable, CaseIterable {
    case desc = "desc"
    case asc = "asc"
}
