//
// TrailerImages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Youtube Images */
public struct TrailerImages: Codable, Hashable {

    public var images: TrailerImagesImages?

    public init(images: TrailerImagesImages? = nil) {
        self.images = images
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case images
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(images, forKey: .images)
    }
}

