//
// AnimeSearchQueryRating.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Available Anime audience ratings&lt;br&gt;&lt;br&gt;&lt;b&gt;Ratings&lt;/b&gt;&lt;br&gt;&lt;ul&gt;&lt;li&gt;G - All Ages&lt;/li&gt;&lt;li&gt;PG - Children&lt;/li&gt;&lt;li&gt;PG-13 - Teens 13 or older&lt;/li&gt;&lt;li&gt;R - 17+ (violence &amp; profanity)&lt;/li&gt;&lt;li&gt;R+ - Mild Nudity&lt;/li&gt;&lt;li&gt;Rx - Hentai&lt;/li&gt;&lt;/ul&gt; */
public enum AnimeSearchQueryRating: String, Codable, CaseIterable {
    case g = "g"
    case pg = "pg"
    case pg13 = "pg13"
    case r17 = "r17"
    case r = "r"
    case rx = "rx"
}
