//
// AnimeSearchQueryType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Available Anime types */
public enum AnimeSearchQueryType: String, Codable, CaseIterable {
    case tv = "tv"
    case movie = "movie"
    case ova = "ova"
    case special = "special"
    case ona = "ona"
    case music = "music"
}
