# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '15.0'

def common_pods_for_target
    pod 'Firebase/Core'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Phone'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Messaging'
    pod 'Firebase/Auth'
    pod 'Firebase/Analytics'
    pod 'Firebase/Performance'
    pod 'Firebase/AppCheck'
end

target 'Fungi Incognita' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fungi Incognita
  common_pods_for_target

end
