openapi: 3.0.3
info:
  title: InshortsAPI
  description: Inshorts is an app which provides news from different sources and presents them under 60 words. This API Scraps content from the Inshorts website and provides it in easy to use JSON Format.
  version: 1.0.0
servers:
- url: https://inshorts-api.herokuapp.com/news
tags:
- name: articles
  description: News articles
paths:
  /news/:
    get:
      tags:
      - data
      summary: News List
      operationId: newsGet
      parameters:
      - name: category
        in: query
        description: the category of news
        required: true
        schema:
          type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleList'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    ArticleList:
      required:
      - category
      type: object
      properties:
        status:
          type: string
        category:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/Article'
    ErrorModel:
      required:
      - error
      type: object
      properties:
        error:
          type: string
    Article:
      required:
      - url
      type: object
      properties:
        author:
          type: string
        content:
          type: string
        date:
          type: string
        urlToImage:
          type: string
        readMoreUrl:
          type: string
        time:
          type: string
        title:
          type: string
        url:
          type: string
