//
// ArticleList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ArticleList: Codable, Hashable {

    public var status: String?
    public var category: String
    public var data: [Article]?

    public init(status: String? = nil, category: String, data: [Article]? = nil) {
        self.status = status
        self.category = category
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case category
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(category, forKey: .category)
        try container.encodeIfPresent(data, forKey: .data)
    }
}
